use glam::Vec3;

use crate::Shape;

/// Vertex in a [`Mesh`].
///
/// Use feature `bytemuck` to easily convert to bytes.
#[repr(C)]
#[derive(Clone, Debug, Copy)]
pub struct Vertex {
    pub position: Vec3,
    pub color: [f32; 4],
}

#[cfg(feature = "bytemuck")]
unsafe impl bytemuck::Pod for Vertex {}

#[cfg(feature = "bytemuck")]
unsafe impl bytemuck::Zeroable for Vertex {}

/// Mesh generated by scissor.
#[derive(Clone, Debug)]
pub struct Mesh {
    pub vertices: Vec<Vertex>,
    pub indices: Vec<u32>,
}